CodeSystem: MedicationRequestStatusReasonCS
Id: medicationrequest-status-reason-cs
Title: "Kenya MedicationRequest Status Reason Code System"
Description: "MedicationRequest status reason codes from MOH-KENYA KNHTS"
* ^url = "https://fhir.dha.go.ke/nccp/CodeSystem/medicationrequest-status-reason-cs"
* ^status = #active
* ^caseSensitive = true
* #ALLERGY "Allergy"
* #OUT-OF-STOCK "Out of stock"
* #DRUG-INTERACTION "Drug interaction"
* #ALTERNATIVE-THERAPY-AVAILABLE "Alternative therapy available"
* #CLARIFICATION-REQUIRED "Clarification required"
* #DRUG-LEVEL-TOO-HIGH "Drug level too high"
* #HOSPITAL-ADMISSION "Hospital admission"
* #LABORATORY-INTERFERENCE "Laboratory interference"
* #DRUG-NOT-AVAILABLE "Drug not available"
* #PREGNANCY "Pregnancy"
* #DRUG-DRUG-INTERACTION "Drug-drug interaction"
* #DUPLICATE-THERAPY "Duplicate therapy"
* #SIDE-EFFECTS "Side effects"
* #SURGERY "Surgery"
* #WASHOUT-PERIOD "Washout period"
* #CANCELLED-BY-PRESCRIBER "Cancelled By Prescriber"
* #CANCELLED-BY-PATIENT "Cancelled By Patient"
* #ADVERSE-REACTION "Adverse Reaction"
* #REPLACED "Replaced"

CodeSystem: RouteOfAdministrationCS
Id: route-of-administration-cs
Title: "Kenya PPB Route of Administration Code System"
Description: "Route of administration codes from MOH-PPB KNHTS"
* ^url = "https://fhir.dha.go.ke/nccp/CodeSystem/route-of-administration-cs"
* ^status = #active
* ^caseSensitive = true
* #RT10001 "Buccal"
* #RT10002 "Dental"
* #RT10003 "Epidural"
* #RT10004 "Hemodialysis"
* #RT10005 "Implantation"
* #RT10006 "In Vitro"
* #RT10007 "Inhalation"
* #RT10008 "Injection"
* #RT10009 "Intraarterial"
* #RT10010 "Intraarticular"
* #RT10011 "Intracavernosal"
* #RT10012 "Intradermal"
* #RT10013 "Intramuscular"
* #RT10014 "Intraocular"
* #RT10015 "Intraperitoneal"
* #RT10016 "Intrapleural"
* #RT10017 "Intrathecal"
* #RT10018 "Intrauterine"
* #RT10019 "Intravesical"
* #RT10020 "Irrigation"
* #RT10021 "Miscellaneous"
* #RT10022 "Mucous Membrane"
* #RT10023 "Nasal"
* #RT10024 "Ophthalmic"
* #RT10025 "Oral"
* #RT10026 "Otic"
* #RT10027 "Perfusion"
* #RT10028 "Rectal"
* #RT10029 "Subcutaneous"
* #RT10030 "Sublingual"
* #RT10031 "Topical"
* #RT10032 "Transdermal"
* #RT10033 "Translingual"
* #RT10034 "Urethral"
* #RT10035 "Vaginal"
* #RT10036 "Intravenous"
* #RT10037 "Intravitreal"
* #RT10038 "Intrapulmonary"
* #RT10039 "Nebuliser"

CodeSystem: MedicationAdminStatusReasonCS
Id: medication-admin-status-reason-cs
Title: "Kenya Medication Administration Status Reason Code System"
Description: "Medication administration status reason codes from MOH-KENYA KNHTS"
* ^url = "https://fhir.dha.go.ke/nccp/CodeSystem/medication-admin-status-reason-cs"
* ^status = #active
* ^caseSensitive = true
* #PATIENT-REFUSED-MEDICATION "Patient refused medication"
* #MEDICATION-NOT-AVAILABLE "Medication not available"
* #PATIENT-UNCONSCIOUS "Patient unconscious"
* #CLINICAL-HOLD "Clinical hold"
* #ADVERSE-DRUG-REACTION "Adverse drug reaction"
* #MEDICATION-DOSE-OMITTED "Medication dose omitted"
* #ALLERGY-TO-MEDICATION "Allergy to medication"
* #PATIENT-REFUSED "Patient refused"
* #LAB-OUT-OF-RANGE "Lab Out Of Range"
* #TOXICITY "Toxicity"
* #DISEASE-PROGRESSION "Disease Progression"
* #PATIENT-DEATH "Patient Death"
